version: "3"
rpc:
  listen: tcp://127.0.0.1:6001

server:
  command: "php vendor/bin/roadrunner-worker" # التشغيل المباشر للـ worker
  relay: pipes

http:
  address: 0.0.0.0:8000
  pool:
    num_workers: 10 # هذا هو عدد المسارات المتوازية التي ستشرحها للأستاذ
    debug: false

logs:
  level: error